[Input]
; Sensitivity when in "control mode" (rotating camera around the dragon)
ControlSensitivity=0.16

[Debugging]
; Spawns a console window with a real-time log from the DLL
EnableConsole=FALSE
; Writes all logs into IOTDPatch.log file
EnableLogFile=FALSE
; Minimum logging level: Error > Warning > Info > Verbose > VeryVerbose
MinimalLogVerbosity=Info