[Input]
; Sensitivity when in "control mode" (rotating camera around the dragon)
; Value will be clamped between 0 and 2 (1 = default, <1 slower, >1 faster)
; Default: 1
ControlSensitivity=1

[Debugging]
; Spawns a console window with a real-time log from the DLL
; Default: FALSE
EnableConsole=FALSE
; Writes all logs into IOTDPatch.log file
; Default: FALSE
EnableLogFile=FALSE
; Minimum logging level: Error > Warning > Info > Verbose > VeryVerbose
; Default: Info
MinimalLogVerbosity=Info